server:
  port: 8080
  servlet:
    context-path: /portfolio

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/todo_db
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:19940119Nk}
    
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true